"""Initial migration.

Revision ID: 9f6dcf9ffa9d
Revises: 
Create Date: 2021-03-21 12:00:36.726889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6dcf9ffa9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('genres', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'genres')
    # ### end Alembic commands ###
